name: ReleaseCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release to S3
      run: bash scripts/pipeline/release.sh ${{secrets.BUCKET_NAME}} ${{secrets.DISTRIBUTION_ID}} ${{secrets.ACCESS_KEY}} ${{secrets.SECRET_ACCESS_KEY}}